//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace test.Models
{
    public partial class Excercise
    {
        public int Id { get; set; }
        
        public string ExcerciseName { get; set; }
        
        public System.DateTime ExcerciseDate { get; set; }
       
        public int DurationInMin { get; set; }
    }
}
